name: project_env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - openmm==8.1.1
  - pdbfixer==1.9
  - ruamel.yaml==0.17.21
  - pytest==8.1.1
  - cwltool==3.1.20240404144621
  - cwl-utils==0.33
